name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "00 0 * * 1"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Timezone
          config_timezone: "Europe/Kyiv"
          # Most used language
          plugin_languages: yes
          # Achievements
          plugin_achievements: yes
          # Music Plug
          plugin_music: yes
          plugin_music_provider: "apple"
          plugin_music_playlist: "https://music.apple.com/ua/playlist/meow-mp3/pl.u-BNA6zJJCAMYroz"
